AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'python3.8

  Sample SAM Template for sam-cicd

  '
Globals:
  Function:
    Timeout: 30
    Runtime: python3.8
Parameters:
  EnvType:
    Type: String
    Description: Target execution environment type
    AllowedValues:
    - dev
    - test
    - prod
    Default: prod
Resources:
  RandomNumberFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://tci-sam-code/af9695958b296a25e35d492ced54bfb6
      Handler: app.lambda_handler
      Environment:
        Variables:
          ENV_TYPE:
            Ref: EnvType
      Events:
        RandomNumberApi:
          Type: Api
          Properties:
            Path: /random-numbers
            Method: post
Outputs:
  RandomNumberApi:
    Description: API Gateway endpoint URL for Prod stage for Random Number function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/random-number

