# template.yaml

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for sam-cicd

Parameters:
  EnvType:
    Type: String
    Description: Target execution environment type
    AllowedValues:
      - dev
      - test
      - prod
    Default: prod

Conditions:
  IsProd: !Equals
    - !Ref EnvType
    - prod

Globals:
  Function:
    Timeout: 30
    Runtime: python3.8
    AutoPublishAlias: live

Resources:
  RandomNumberFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: random_numbers/
      Handler: app.lambda_handler
      Environment:
        Variables:
          ENV_TYPE: !Ref EnvType
      Events:
        RandomNumberApi:
          Type: Api
          Properties:
            Path: /random-numbers
            Method: post

  RandomNumberFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ''
          - - /aws/lambda/
            - Ref: RandomNumberFunction
      RetentionInDays: 14

  RandomNumberFunctionAliasErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: Errors
      Namespace: "AWS/Lambda"
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Period: 60
      Statistic: Sum
      Threshold: 2
      AlarmDescription: Fire alarm if more than 3 errors occur in any 60 second period
      Dimensions:
        - Name: Resource
          Value: !Sub "${RandomNumberFunction}:live"
        - Name: FunctionName
          Value: !Ref RandomNumberFunction
      # AlarmActions:
      #   - ARN 1
      #   - ARN 2
      # Actions to take when transition back to ok state
      # OKActions: 
      #   - ARN 1
      #   - ARN 2
      TreatMissingData: notBreaching

Outputs:
  RandomNumberApi:
    Description: "API Gateway endpoint URL for Prod stage for Random Number function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/random-numbers"
